version: '3.8'

services:
    app:
        build:
            context:
            dockerfile: ./DOCKERFILE
        container_name: shopingo_laravel
        volumes:
            - ./app:/var/www
        depends_on:
            - db


    nginx:
        image: nginx:alpine
        container_name: shopingo_nginx
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - app


    db:
        image: mysql:8
        container_name: shopingo_db
        restart: always
        enviroment:
            - MYSQL_DATABASE: shopingo
            - MYSQL_ROOT_PASSWORD: rootpass
            - MYSQL_USER: admin
            - MYSQL_PASSWORD: secret
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
